### Create a question

POST http://127.0.0.1:5000/api/questions
Content-Type: application/json

{
    "name": "Mark",
    "text": "This is another note that I hope works",
    "repo": "repo",
    "live": "live"
}

### View question
GET http://127.0.0.1:5000/api/questions
Content-Type: application/json

### Edit a question
Patch http://127.0.0.1:5000/api/questions/606f7a0b05835c1885d0ced3
Content-Type: application/json

{
"answered": true
}


### Delete a question
DELETE http://127.0.0.1:5000/api/questions/606f637c1c251b08c76a5334
Content-Type: application/json
